### ISSUE TITLE
Historical Reference and Testing

### ISSUE THREAD

**Issue by BradKML** [xulihang/AnimatedQRCodeReader#1]
The inspiration for this app has noted research and visualization on speed. It is good to consider that as part of AnimatedQRCodeReader, and possibly note the pareto frontier when given a list of test results. An extra info to note: it would be useful to have a "test mode" for phone-to-phone communication, and see if shutter speed and resolution can have an effect.

- https://divan.dev/posts/animatedqr/
- https://divan.dev/posts/fountaincodes/
- https://en.wikipedia.org/wiki/Multi-objective_optimization

**Comment by xulihang** [comment]
As the testing results may vary on different senders and receivers, I don't think it is very meaningful.

**Comment by BradKML** [comment]
Perhaps a recommended setting will suffice (with Google flagships as a mock-base).

**Comment by xulihang** [comment]
I do have done a simple test (see the [blog](https://www.dynamsoft.com/codepool/transfer-data-with-animated-qr-codes.html)). For flagship phones, we can set the size to the largest (2.9KB) and set the time interval small (100~200ms).
