### ISSUE TITLE
The version of DynamicSoft DBR and DCE

### ISSUE THREAD

**Issue by shgoupf** [xulihang/AnimatedQRCodeReader#2]
Hey,

I am trying to build the android app for the reader. Seems like the latest version 8.9.0 of DynamicSoft DBR is not working. Could you please share which version should be used to build this android app?

**Comment by xulihang** [comment]
DCE 1.x and DBR 8.6 should work. You can use maven instead. Check out this: https://www.dynamsoft.com/codepool/enhance-camera-scanning-with-DCE.html

**Comment by shgoupf** [comment]
Thanks a lot. DCE 1.x and DBR 8.6 works pretty well, :)
