### ISSUE TITLE
Cannot use scanner.html offline due to Dynamsoft licensing?

### ISSUE THREAD

**Issue by Core2DuoKing** [xulihang/AnimatedQRCodeReader#3]
Hello,

I'm enjoying AnimatedQRCodeReader and it works really well it's fast enough, simple, and works on multiple devices (PC to PC is my real need). I'm running into an issue though. Scanner.html works great when connected to the internet, but it's not able to initialize the camera while not having any internet access. I'm assuming this has something to do with dynamsoft licensing check?

Are there any plans in the future to get away from the dynamsoft barcode reader so that this can be used consistently without a connection to the internet, or without having to buy their license (I think I saw it was around $1,400 per year.)?

Thank you for all that you do.

**Comment by xulihang** [comment]
I will check with my manager next week to see if there could be a free PWA version hosted on Dynamsoft.com.

**Comment by xulihang** [comment]
You can also [apply for your own license](https://www.dynamsoft.com/customer/license/trialLicense?product=dbr) to use it first.

After you connect to the license server for initialization, the private trial license can be used offline for 30 days and a full license can be used offline for 90 days.
