### ISSUE TITLE
Migrate from DBR to something else

### ISSUE THREAD

**Issue by hexahigh** [xulihang/AnimatedQRCodeReader#4]
Hey, i know that this project is a little old now and hasnt been updated in a while but i was wondering if it was possible to migrate from DBR to something else.
This project is really cool and very usefull but the fact that its powered by a closed-source engine means that if dynamsoft were to go bankrupt you would have no easy way to decrypt your files.

**Comment by hexahigh** [comment]
And also the fact that you can only use it for 30 days before the free license expires

**Comment by xulihang** [comment]
Dynamsoft Barcode Reader has better performance.

It can be replaced with libraries like [zxing-js](https://github.com/zxing-js/library/) with a bit of modification. You are free to do this by yourself.

**Comment by hexahigh** [comment]
The code format that this project uses is regular qr code right?

**Comment by xulihang** [comment]
Yes.

**Comment by hexahigh** [comment]
Thank you
